root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./build/main"
  cmd = "make live"
  delay = 0
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  exclude_file = []
  exclude_regex = ["_test.go", "_templ.go", "README.md"]
  include_ext = ["go", "templ", "html"]
  kill_delay = "0s"
  log = "build-errors.log"
  pre_cmd = []
  rerun_delay = 0

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[screen]
  clear_on_rebuild = true 
  keep_scroll = true
